### ISSUE TITLE
Error: Cannot find module 'rollup/bin/rollup'

### ISSUE THREAD

**Issue by andrericardo** [chartjs/chartjs-chart-financial#61]
Trying to build the project, got an error after running `gulp build`, what am I doing wrong?

Steps to reproduce
\> git clone https://github.com/chartjs/chartjs-chart-financial/
\> cd chartjs-chart-financial
\> npm install
\> gulp build

Confirmed there were no missing dependencies
> ➜  chartjs-chart-financial git:(master) npm install
audited 7632 packages in 6.617s
found 0 vulnerabilities

> ➜  chartjs-chart-financial git:(master) gulp build
[00:11:53] Using gulpfile ~/VirtualBox/Win10/chartjs-chart-financial/gulpfile.js
[00:11:53] Starting 'build'...
[00:11:53] Starting 'rollupTask'...
[00:11:53] 'rollupTask' errored after 6.31 ms
[00:11:53] Error: Cannot find module 'rollup/bin/rollup'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.resolve (internal/modules/cjs/helpers.js:28:19)
    at run (/Users/andre/VirtualBox/Win10/chartjs-chart-financial/gulpfile.js:42:21)
    at rollupTask (/Users/andre/VirtualBox/Win10/chartjs-chart-financial/gulpfile.js:51:3)
    at bound (domain.js:400:14)
    at runBound (domain.js:413:12)
    at asyncRunner (/Users/andre/VirtualBox/Win10/chartjs-chart-financial/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
[00:11:53] 'build' errored after 11 ms

\> node --version
v11.10.0
\> npm --version
6.7.0
\> gulp --version
CLI version: 2.2.0
Local version: 4.0.2

**Comment by benmccann** [comment]
Thanks for the fix
